
services:
  rest-api:
    build:
      context: './src/Api'
      dockerfile: dockerfile
    environment:
      - NODE_ENV=production
    env_file: ./src/Api/.env
    networks:
      - backend
    ports:
      - "3000:3000"

  socket: 
    build:
      context: './src/Socket'
      dockerfile: dockerfile
    environment:
      - NODE_ENV=production
    env_file: ./src/Socket/.env
    networks:
      - backend
    ports:
      - "3002:3002"

networks:
  backend:
    driver: bridge